# Generated by Django 2.1.4 on 2019-08-25 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='last_fetch_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotspotsource',
            name='code',
            field=models.PositiveSmallIntegerField(default=1, help_text='来源编码', unique=True),
            preserve_default=False,
        ),
    ]
