# Generated by Django 2.1.4 on 2019-08-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0002_auto_20190825_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotspot',
            name='last_fetch_time',
        ),
    ]
