# Generated by Django 2.2 on 2019-08-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0004_auto_20190825_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotspot',
            options={'ordering': ('-created_time',)},
        ),
    ]
