# Generated by Django 2.2 on 2019-08-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0005_auto_20190826_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='uri',
            field=models.URLField(help_text='热点uri', max_length=1024),
        ),
    ]
