# Generated by Django 2.2 on 2019-08-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0006_auto_20190826_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotsource',
            name='last_fetch_data_time',
            field=models.DateTimeField(help_text='最后获取数据的时间', null=True),
        ),
    ]
