# Generated by Django 2.2.4 on 2019-08-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot', '0008_hotspotsource_source_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspotsource',
            name='icon',
            field=models.URLField(blank=True, help_text='图标', max_length=256),
        ),
    ]
